"""add property listings

Revision ID: 6e04aadfdcef
Revises: 21483b6f56cd
Create Date: 2026-09-29 00:40:22.529397
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6e04aadfdcef"
down_revision: Union[str, None] = "20260928_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_listings',
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('price_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('initial_dp', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('num_bedrooms', sa.Integer(), nullable=True),
    sa.Column('num_bathrooms', sa.Integer(), nullable=True),
    sa.Column('layout_type', sa.String(length=255), nullable=True),
    sa.Column('village_name', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('amenity_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nearby_places', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('nearby_establishments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('has_kitchen', sa.Boolean(), nullable=True),
    sa.Column('has_backyard', sa.Boolean(), nullable=True),
    sa.Column('has_garage', sa.Boolean(), nullable=True),
    sa.Column('garage_spaces', sa.Integer(), nullable=True),
    sa.Column('sync_status', sa.String(length=30), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_property_listings_listing_id'), 'property_listings', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_listings_listing_id'), table_name='property_listings')
    op.drop_table('property_listings')
    # ### end Alembic commands ###
