"""add property listing status

Revision ID: 891284426ae5
Revises: bf28bc395c16
Create Date: 2026-09-29 21:23:23.383455
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891284426ae5'
down_revision: Union[str, None] = 'bf28bc395c16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_listings', sa.Column('status', sa.String(length=20), server_default='AVAILABLE', nullable=False))
    op.create_index(op.f('ix_property_listings_status'), 'property_listings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_property_listings_status'), table_name='property_listings')
    op.drop_column('property_listings', 'status')
    # ### end Alembic commands ###
