"""add agent management

Revision ID: fd97657259dd
Revises: e3f1f11294c7
Create Date: 2026-09-29 17:34:53.050139
"""

from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd97657259dd'
down_revision: Union[str, None] = 'e3f1f11294c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=40), nullable=True),
    sa.Column('agent_location', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('star_rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('assignments_count', sa.Integer(), nullable=False),
    sa.Column('transactions_count', sa.Integer(), nullable=False),
    sa.Column('completed_sales', sa.Integer(), nullable=False),
    sa.Column('total_sales', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('performance_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('sync_status', sa.String(length=24), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    agents = sa.table(
        'agents',
        sa.column('agent_id', sa.String()),
        sa.column('full_name', sa.String()),
        sa.column('phone_number', sa.String()),
        sa.column('agent_location', sa.String()),
        sa.column('latitude', sa.Numeric(9, 6)),
        sa.column('longitude', sa.Numeric(9, 6)),
        sa.column('star_rating', sa.Numeric(2, 1)),
        sa.column('assignments_count', sa.Integer()),
        sa.column('transactions_count', sa.Integer()),
        sa.column('completed_sales', sa.Integer()),
        sa.column('total_sales', sa.Numeric(16, 2)),
        sa.column('total_commission', sa.Numeric(16, 2)),
        sa.column('performance_score', sa.Numeric(6, 2)),
        sa.column('status', sa.String()),
        sa.column('sync_status', sa.String()),
        sa.column('last_synced_at', sa.DateTime()),
        sa.column('created_at', sa.DateTime()),
        sa.column('updated_at', sa.DateTime()),
    )
    now = datetime.utcnow()
    defaults = {
        'phone_number': None,
        'assignments_count': 0,
        'transactions_count': 0,
        'completed_sales': 0,
        'total_sales': 0,
        'total_commission': 0,
        'performance_score': 0,
        'status': 'ACTIVE',
        'sync_status': 'DEMO',
        'last_synced_at': None,
        'created_at': now,
        'updated_at': now,
    }
    op.bulk_insert(
        agents,
        [
            {
                **defaults,
                'agent_id': 'AGT-0001', 'full_name': 'Maria Santos',
                'agent_location': 'BGC, Taguig', 'latitude': 14.5547,
                'longitude': 121.0244, 'star_rating': 4.8,
            },
            {
                **defaults,
                'agent_id': 'AGT-0002', 'full_name': 'John Reyes',
                'agent_location': 'Makati City', 'latitude': 14.5547,
                'longitude': 121.0167, 'star_rating': 4.6,
            },
            {
                **defaults,
                'agent_id': 'AGT-0003', 'full_name': 'Angela Cruz',
                'agent_location': 'Quezon City', 'latitude': 14.6760,
                'longitude': 121.0437, 'star_rating': 4.9,
            },
            {
                **defaults,
                'agent_id': 'AGT-0004', 'full_name': 'Michael Garcia',
                'agent_location': 'Pasig City', 'latitude': 14.5764,
                'longitude': 121.0851, 'star_rating': 4.5,
            },
            {
                **defaults,
                'agent_id': 'AGT-0005', 'full_name': 'Sofia Mendoza',
                'agent_location': 'Parañaque City', 'latitude': 14.4793,
                'longitude': 121.0198, 'star_rating': 4.7,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
